# Generated by Django 4.0.3 on 2022-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_documento_data_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
