# Generated by Django 4.0.3 on 2022-10-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_facturas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facturas',
            new_name='Factura',
        ),
    ]
