# Generated by Django 4.0.3 on 2022-10-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_rename_facturas_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.area'),
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documento.proveedor'),
        ),
    ]
