# Generated by Django 4.0.3 on 2022-12-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0008_proveedor_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('Pedido', 'Pedido'), ('Requerimiento', 'Requerimiento')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encargadoarea',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
