# Generated by Django 4.0.3 on 2022-12-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0009_alter_documento_tipo_alter_encargadoarea_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('Evaluando', 'Evaluando'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Evaluando', max_length=20, null=True),
        ),
    ]
